language: go
go_import_path: github.com/simukti/sqldb-logger

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

allow_failures:
  - master

git:
  depth: 1

env:
  - GO111MODULE=on

install: true

branches:
  only:
    - master

before_install:
  - go get -u -v github.com/mattn/goveralls

script:
  - go vet
  - test -z "$(go fmt ./...)" # fail if not formatted properly
  - go test -v -race -coverprofile=coverage.out -covermode=atomic -tags=unit ./...

after_success:
  - $GOPATH/bin/goveralls -v -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
