language: go
install: true
go_import_path: github.com/simukti/sqldb-logger

go:
  - "1.11"
  - "1.12"
  - "1.13"
  - master

git:
  depth: 1

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on

allow_failures:
  - master

branches:
  only:
    - master

before_install:
  - go get -u -v github.com/mattn/goveralls
  - go mod vendor -v

script:
  - go vet
  - test -z "$(go fmt ./...)" # fail if not formatted properly
  - go test -v -race -coverprofile=coverage.out -covermode=atomic -tags=unit ./...

after_success:
  - $GOPATH/bin/goveralls -v -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
